name: turnify
description: "Turnify: aplicación que te dara la facilidad de gestionar tus turnos."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo_Turnify.png
    - assets/icons/icono_turnify.png
    - assets/icons/turnify_icon_1024.png
    - assets/icons/turnify_foreground.png
    - assets/icons/turnify_background.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/turnify_icon_1024.png"
  android_adaptive_icon:
    foreground_image: "assets/icons/turnify_foreground.png"
    background_image: "assets/icons/turnify_background.png"